export const clerkAppearance = {
  variables: {
    colorPrimary: "#F97316",
    colorBackground: "#ffffff",
    colorText: "#0F2640",
    colorTextSecondary: "#6B7C8F",
    colorInputBackground: "#ffffff",
    colorInputText: "#0F2640",
    colorDanger: "#DC2626",
    borderRadius: "0px",
  },
  elements: {
    rootBox: { width: "100%" },
    card: { boxShadow: "none", border: "none", padding: 0, background: "transparent" },
    headerTitle: {
      fontFamily: "Archivo, sans-serif",
      fontWeight: "900",
      color: "#14375F",
      fontSize: "22px",
    },
    headerSubtitle: { color: "#6B7C8F", fontSize: "14px" },
    formButtonPrimary: {
      fontWeight: "700",
      fontSize: "15px",
      height: "48px",
      backgroundColor: "#F97316",
      borderRadius: "0",
    },
    socialButtonsBlockButton: {
      height: "44px",
      borderRadius: "0",
      border: "1.5px solid #CBD5E1",
    },
    formFieldInput: {
      border: "1.5px solid #CBD5E1",
      height: "48px",
      borderRadius: "0",
      fontSize: "15px",
    },
    formFieldLabel: {
      fontFamily: "JetBrains Mono, monospace",
      textTransform: "uppercase" as const,
      fontSize: "11px",
      letterSpacing: "0.08em",
      color: "#2D4258",
    },
    footerActionLink: { color: "#14375F", fontWeight: "600" },
    footerActionText: { color: "#6B7C8F" },
    dividerText: { color: "#6B7C8F", fontSize: "12px" },
    identityPreviewText: { color: "#14375F" },
    formResendCodeLink: { color: "#F97316" },
    otpCodeFieldInput: { border: "1.5px solid #CBD5E1", borderRadius: "0", height: "48px" },
  },
};
